<?php
namespace frontend\models;
use yii\base\Model;

class LoginForm extends Model{
    public $username;
    public $password_hash;
    public $captcha;
    public $auto_login;
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
    public function rules()
    {
        return [
            [['username','password_hash'],'required'],
            ['auto_login','safe'],
            ['captcha','captcha','captchaAction'=>'member/captcha']
        ];
    }
    public function check_login(){
        $member=Member::findOne(['username'=>$this->username,'status'=>1]);
        if ($member){
            if (\Yii::$app->security->validatePassword($this->password_hash,$member->password_hash)){
                $member->last_login_time=time();
                $member->last_login_ip=\Yii::$app->request->userIP;
                $member->save(0);
                $time=$this->auto_login?24*3600:0;
                \Yii::$app->user->login($member,$time);
                \Yii::$app->session->setFlash('success','登录成功');
                return true;
            }
            $this->addError('username','用户名或密码错误');
        }
    }
}
